import './global.css';
import { ReactNode } from 'react';
import ClientLayout from './ClientLayout';

export const metadata = {
  title: 'HRXpert',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* ✅ Hand off to client wrapper */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
